# GAE

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    sudo apt-get update && sudo apt-get install google-cloud-sdk
    echo ${GOOGLE_CLIENT_SECRET} > client-secret.json
    gcloud auth activate-service-account --key-file client-secret.json
    gcloud --quiet --verbosity=error app deploy ./app.yaml --no-promote --version=2 --project $CLOUDSDK_CORE_PROJECT