# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: google/cloud-sdk

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - lsb_release -a 
          - apt-get update
          - apt-get -y install php7.2
#          - apt-get -y install php7.2 php7.2-cli php7.2-common php7.2-opcache php7.2-curl php7.2-mbstring php7.2-mysql php7.2-zip php7.2-xml
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - echo ${GOOGLE_CLIENT_SECRET} > client-secret.json
          - gcloud auth activate-service-account --key-file client-secret.json
          - gcloud --quiet --verbosity=error app deploy app.yaml --no-promote --version=2 --project $CLOUDSDK_CORE_PROJECT
